#!/bin/sh

notification(){
	notify-send "Now Playing: Lofi Radio ☕️ "
}

notification1(){
	notify-send "Now Playing: Lofi Girl ☕️ "
}

notification2(){
	notify-send "Now Playing: Chillhop ☕️ "
}

notification3(){
	notify-send "Now Playing: Box Lofi  ☕️ "
}

notification4(){
	notify-send "Now Playing: The Bootleg Boy ☕️ "
}

notification5(){
	notify-send "Now Playing: Radio Spinner ☕️ "
}
	
notification6(){
	notify-send "Now Playing: SmoothChill ☕️ "
}

notification7(){
	notify-send "Now Playing: Anime Lofi ☕️ "
}

notification8(){
	notify-send "Now Playing: Lofi Hip Hop ☕️ " 
}

notification9(){
	notify-send "Now Playing: J-Pop Cafe Music ☕️ "
}

notification10(){
	notify-send "Now Playing: Tokyo Cafe ☕️ "
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill\n"
	printf "7. Anime Lofi\n"
	printf "8. Lofi Hip Hop\n"
	printf "9. J-Pop Cafe Music\n"
	printf "10. Tokyo Cafe"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification1 ;
				mpv "https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification2 ;
				mpv "http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification3 ;
				mpv "http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification4 ;
				mpv "http://stream.zeno.fm/0r0xa792kwzuv"
			break
			;;
		5)
			notification5 ;
				mpv "https://live.radiospinner.com/lofi-hip-hop-64"
			break
			;;
		6)
			notification6 ;
				mpv "https://media-ssl.musicradio.com/SmoothChill"
			break
			;;
		7)
			notification7 ;
				mpv "https://www.youtube.com/watch?v=pbp6ktKLcfM" --no-video
			break
		 ;;
	  8)
			notification8 ;
				mpv "https://www.youtube.com/watch?v=5qap5aO4i9A" --no-video
			break
		 ;;
		9)
			notification9 ;
				mpv "https://www.youtube.com/watch?v=pbqbnSQ5pxw" --no-video
			break
			;;
		10)
			notification10 ; 
				mpv "https://www.youtube.com/watch?v=6uddGul0oAc" --no-video
			break
			;;
	
	esac
}

pkill -f http || main
