#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#6272A4

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config pointer_motion_interval 7


# Autostart
nitrogen --restore
picom --config ~/.config/picom.conf & 
#xss-lock --transfer-sleep-lock -- i3lock -c 000000 --nofork &
exec ~/.config/polybar/launch.sh &
#mpd-notification & 
xsetroot -cursor_name left_ptr &
#xautolock -time 20 -locker "i3lock -c 000000" &
